#!/bin/bash

php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy -f
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento setup:di:compile
php bin/magento indexer:reindex